@CryV.Net.Server.Blazor_HostAddress = https://localhost:7060

GET {{CryV.Net.Server.Blazor_HostAddress}}/api/players/0

###

GET {{CryV.Net.Server.Blazor_HostAddress}}/api/players

###

GET {{CryV.Net.Server.Blazor_HostAddress}}/api/vehicles

###

GET {{CryV.Net.Server.Blazor_HostAddress}}/api/vehicles/0

###
