name: Build .NET

on: repository_dispatch

jobs:
  build:
    if: github.event.action == 'run_build'
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.x
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Copy Files
      shell: cmd
      run: |
        mkdir out
        mkdir out\client\dotnet\runtime
        mkdir out\client\dotnet\resources
        mkdir out\server\gamemode\example\server
        mkdir out\server\gamemode\example\client
        xcopy /S /Y CryV.Net\bin\Release\net7.0 out\client\dotnet\runtime\
        xcopy /S /Y CryV.Net.Client.Core\bin\Release\net7.0 out\client\dotnet\resources\
        xcopy /S /Y CryV.Net.Server.Core\bin\Release\net7.0 out\server\
        xcopy /S /Y CryV.Net.Server.Example\bin\Release\net7.0 out\server\gamemode\example\server\
        xcopy /S /Y CryV.Net.Client.Example\bin\Release\net7.0 out\server\gamemode\example\client\
        
    - uses: actions/upload-artifact@v2-preview
      with:
        name: CryV.Net
        path: out/
